---
- name: Install minikube
  ansible.builtin.import_tasks: tasks/minikube.yml

- name: Install kubectl
  ansible.builtin.import_tasks: tasks/kubectl.yml

- name: Install helm
  ansible.builtin.import_tasks: tasks/helm.yml

- name: Install Hashicorp stack
  ansible.builtin.import_tasks: tasks/hashicorp.yml

- name: Install cloud CLIs
  ansible.builtin.import_tasks: tasks/cloud.yml
