---
- name: Install Terraform CLI
  become: yes
  block:
    - name: Download HashiCorp GPG key
      apt_key:
        id: AA16FCBCA621E701
        url: https://apt.releases.hashicorp.com/gpg
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
        state: present

    - name: Add HashiCorp repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
        filename: hashicorp

    - name: Update apt and install terraform
      apt:
        name: terraform
        update_cache: yes
        state: present
